### ISSUE TITLE
If a connection issue occurs, how can I learn about it?

### ISSUE THREAD

**Issue by jwoudenberg** [chris-rock/bunyan-logstash-tcp#12]
I have a question: it sometimes occurs that for whatever reason bunyan-logstash-tcp loses its connection, or maybe doesn't connect at all in the first place. Does the library support any way of being made attentive of this fact, so that I can log that back to the user?

**Comment by NinjaTux** [comment]
:+1: I need this too!

**Comment by palmic** [comment]
Yeah +1 from me. I have a related issue - it does not reconnect if my log server restarts or something, so i have to restart whole nodejs process to reconnect log stream. error event callback would be great.

**Comment by chris-rock** [comment]
#13 merged
