### ISSUE TITLE
NodeJs application crashes when logstash server is not reachable

### ISSUE THREAD

**Issue by shah-dhara** [chris-rock/bunyan-logstash-tcp#16]
NodeJS application crashes with following error when the logstash server is not reachable:

ERROR
-------
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

Can you please help me to solve this?

**Comment by shah-dhara** [comment]
I figured out the problem, I didn't handle 'error' event on bunyan tcp stream.
It is there in an example, but was not mentioned in the documentation.

**Comment by chris-rock** [comment]
@shah-dhara Could you post an example or test case? This would help us to catch this error in bunyan-logstash-tcp

**Comment by shah-dhara** [comment]
Sure, error came up as for setting up the stream I wrote the following code 

    stream: bunyantcp.createStream({
            host: '127.0.0.1',
            port: 9998
        })

This was not able to emit the logstash down error and made my NodeJS application crash.
I just changed the code to the following: 


    stream: bunyantcp.createStream({
            host: '127.0.0.1',
            port: 9998
        }).on('error', console.log)
